"""
ACTS-AI MVP — core logic
Case loading, input sanitisation, traceability validation, note assembly,
diff metrics, and audit logging. Kept separate from the UI so it can be
unit-tested and reused by an n8n / API deployment.
"""

import csv
import difflib
import json
import os
from datetime import datetime

CASES_DIR = "cases"
AUDIT_LOG = "audit_log.csv"

# Keys that exist only to document the test design. They must be removed
# before the case is sent to the model, otherwise the model can "cheat" by
# reading the planted answers.
TEST_ONLY_KEYS = {
    "expected_behavior_for_testing",
    "intentional_data_gaps_for_testing",
    "planted_gaps",
    "planted_safety_signal",
    "planted_contradictions",
    "must_not_do",
}


# --------------------------------------------------------------------------
# Case loading and sanitisation
# --------------------------------------------------------------------------

def list_cases(cases_dir=CASES_DIR):
    """Return sorted list of case filenames available on disk."""
    if not os.path.isdir(cases_dir):
        return []
    return sorted(f for f in os.listdir(cases_dir) if f.endswith(".json"))


def load_case(filename, cases_dir=CASES_DIR):
    with open(os.path.join(cases_dir, filename), "r", encoding="utf-8") as fh:
        return json.load(fh)


def strip_test_metadata(obj):
    """Recursively remove evaluation-design keys before sending to the model."""
    if isinstance(obj, dict):
        return {
            k: strip_test_metadata(v)
            for k, v in obj.items()
            if k not in TEST_ONLY_KEYS
        }
    if isinstance(obj, list):
        return [strip_test_metadata(v) for v in obj]
    return obj


_INVISIBLE = "\u200b\u200c\u200d\ufeff\u00a0\u2060"


def _is_blank(value):
    """
    True when a statement carries no readable text.

    Ordinary strip() leaves zero-width and non-breaking characters in place, so
    a statement containing only those looks non-empty in code but renders as a
    bare tag with nothing before it.
    """
    if not isinstance(value, str):
        return not value
    return not value.strip().strip(_INVISIBLE).strip()


def collect_source_ids(obj, found=None):
    """Recursively collect every source_id value present in the case data."""
    if found is None:
        found = set()
    if isinstance(obj, dict):
        for key, value in obj.items():
            if key == "source_id" and isinstance(value, str):
                found.add(value)
            else:
                collect_source_ids(value, found)
    elif isinstance(obj, list):
        for item in obj:
            collect_source_ids(item, found)
    return found


def patient_header(case):
    """
    Build the patient identity line directly from the input JSON.
    Deliberately NOT generated by the model - zero hallucination risk on
    the most identity-critical line of the note.
    """
    demo = case.get("demographics", {}) or {}
    adm = case.get("admission_info", {}) or {}
    meta = case.get("case_metadata", {}) or {}
    age = demo.get("age", "?")
    sex = demo.get("sex", "?")
    weight = demo.get("weight_kg")
    weight_txt = f", {weight} kg" if weight else ""
    day = meta.get("icu_day", "?")
    date = meta.get("note_date", "")
    dx = adm.get("admission_diagnosis", "not documented")
    intub = adm.get("intubation_date")
    intub_txt = f"; intubated {intub}" if intub else ""
    return (
        f"**Daily ICU Progress Note — ICU Day {day}**\n\n"
        f"**Date:** {date} | **Patient:** {age}{sex}{weight_txt}\n\n"
        f"**Admission:** {adm.get('admission_date', 'n/a')} — {dx}{intub_txt}\n"
    )


# --------------------------------------------------------------------------
# Traceability validation (the automated hallucination check)
# --------------------------------------------------------------------------

def validate_traceability(ai_output, case):
    """
    Check every source_id cited by the model against the source_ids that
    actually exist in the input case.

    Returns a dict of metrics used both for the live UI warning and for the
    Phase 6 evaluation table.
    """
    valid_ids = collect_source_ids(case)
    valid_ids.add("NO_DATA")  # sentinel permitted by prompt v1.2

    total_statements = 0
    untagged = []          # statements with no source_ids at all
    invalid_refs = []      # statements citing an id not present in the input
    empty = []             # statements the model emitted with no text at all

    for section in ai_output.get("note_sections", []) or []:
        for st in section.get("statements", []) or []:
            total_statements += 1
            raw = st.get("text") or ""
            text = raw.strip() if isinstance(raw, str) else ""
            ids = st.get("source_ids") or []
            if _is_blank(raw):
                empty.append(section.get("title", "?"))
                continue
            if not ids:
                untagged.append((section.get("title", "?"), text))
                continue
            bad = [i for i in ids if i not in valid_ids]
            if bad:
                invalid_refs.append((section.get("title", "?"), text, bad))

    problems = len(untagged) + len(invalid_refs) + len(empty)
    traceable = total_statements - problems
    pct = round(100 * traceable / total_statements, 1) if total_statements else 0.0

    return {
        "total_statements": total_statements,
        "fully_traceable": traceable,
        "traceability_pct": pct,
        "untagged": untagged,
        "invalid_refs": invalid_refs,
        "empty_statements": empty,
        "unsupported_count": problems,
    }


# --------------------------------------------------------------------------
# Note assembly (JSON -> editable markdown)
# --------------------------------------------------------------------------

def assemble_note(ai_output, case, include_tags=True):
    """Render the structured AI output as an editable markdown note."""
    if not ai_output.get("in_scope", False):
        return (
            "## OUT OF SCOPE — NO NOTE GENERATED\n\n"
            f"**Reason:** {ai_output.get('scope_reason', 'not stated')}\n\n"
            "This patient falls outside the validated pilot population "
            "(adult ICU patient receiving invasive mechanical ventilation). "
            "No draft documentation has been produced."
        )

    parts = [patient_header(case), ""]

    for section in ai_output.get("note_sections", []) or []:
        title = section.get("title", "Untitled")
        statements = section.get("statements", []) or []
        parts.append(f"### {title}")
        if not statements:
            parts.append("_No data provided for this system._")
        for st in statements:
            raw = st.get("text") or ""
            if _is_blank(raw):
                continue  # malformed empty statement; reported in the quality panel
            text = raw.strip()
            if include_tags:
                ids = ", ".join(st.get("source_ids") or []) or "UNTAGGED"
                parts.append(f"- {text} `[{ids}]`")
            else:
                parts.append(f"- {text}")
        parts.append("")

    contradictions = ai_output.get("contradictions", []) or []
    if contradictions:
        parts.append("### Contradictions Flagged for Verification")
        for c in contradictions:
            ids = ", ".join(c.get("source_ids") or [])
            parts.append(f"- {c.get('description', '')} `[{ids}]`")
        parts.append("")

    parts.append(f"**Trajectory:** {ai_output.get('trajectory', 'not stated')}")
    parts.append("")
    parts.append(f"_{ai_output.get('draft_disclaimer', '')}_")
    return "\n".join(parts)


# --------------------------------------------------------------------------
# Diff metrics
# --------------------------------------------------------------------------

def diff_metrics(draft, final):
    """
    Word-level comparison between AI draft and physician-approved note.
    Returns percentage of the draft changed plus word counts.
    """
    draft_words = draft.split()
    final_words = final.split()
    matcher = difflib.SequenceMatcher(None, draft_words, final_words)
    matched = sum(block.size for block in matcher.get_matching_blocks())
    changed_pct = (
        round(100 * (1 - matched / len(draft_words)), 1) if draft_words else 0.0
    )
    return {
        "draft_words": len(draft_words),
        "final_words": len(final_words),
        "unchanged_words": matched,
        "percent_changed": changed_pct,
        "similarity_ratio": round(matcher.ratio() * 100, 1),
    }


def render_diff_html(draft, final):
    """Word-level inline diff as HTML for display in the review screen."""
    matcher = difflib.SequenceMatcher(None, draft.split(), final.split())
    out = []
    for tag, i1, i2, j1, j2 in matcher.get_opcodes():
        old = " ".join(draft.split()[i1:i2])
        new = " ".join(final.split()[j1:j2])
        if tag == "equal":
            out.append(old)
        elif tag == "delete":
            out.append(f"<span style='background:#ffd6d6;text-decoration:line-through'>{old}</span>")
        elif tag == "insert":
            out.append(f"<span style='background:#d6f5d6'>{new}</span>")
        elif tag == "replace":
            out.append(f"<span style='background:#ffd6d6;text-decoration:line-through'>{old}</span>")
            out.append(f"<span style='background:#d6f5d6'>{new}</span>")
    return " ".join(out)


# --------------------------------------------------------------------------
# Audit log
# --------------------------------------------------------------------------

AUDIT_FIELDS = [
    "timestamp", "case_id", "case_type", "model", "prompt_version",
    "in_scope", "trajectory", "decision", "reviewer",
    "total_statements", "traceability_pct", "unsupported_count",
    "missing_data_count", "contradictions_count",
    "percent_changed", "review_seconds",
    "edit_unknown_tags", "edit_absence_conflicts",
    "edit_cross_section_conflicts", "edit_untagged_additions",
    "flags_acknowledged", "reviewer_comment",
]


# --------------------------------------------------------------------------
# Post-edit consistency check
#
# The AI draft is validated for traceability before the physician sees it.
# These functions re-validate the note AFTER physician editing, because a
# physician edit can introduce a statement that is untraceable, that asserts
# something the source data marks as absent, or that contradicts another
# section. The physician remains free to add clinical knowledge the structured
# data does not contain - the system flags, it does not block.
# --------------------------------------------------------------------------

import re  # noqa: E402

TAG_PATTERN = re.compile(r"`\[([^\]]*)\]`")

ABSENCE_MARKERS = (
    "not documented", "undocumented", "not available", "not recorded",
    "not provided", "missing", "no data", "unavailable", "not performed",
    "not stated", "cannot be confirmed", "cannot be determined",
)


_NEGATION_START = re.compile(r"^\s*(?:\d+\.\s*)?no\b", re.IGNORECASE)

_ABSENCE_CONTEXT = (
    "document", "available", "record", "provid", "report", "perform",
    "result", "assess", "data",
)


def _has_absence_marker(text):
    """
    True when a statement asserts that something is absent.

    Two phrasings must both be recognised:
      "stress ulcer prophylaxis is not documented"      -> explicit marker
      "no arterial blood gas results were available"    -> leading negation
    Missing the second form causes correct absence statements to be flagged as
    if they asserted content.
    """
    low = text.lower()
    if any(marker in low for marker in ABSENCE_MARKERS):
        return True
    if _NEGATION_START.match(low) and any(c in low for c in _ABSENCE_CONTEXT):
        return True
    return False


def parse_tagged_lines(note_text):
    """
    Walk the edited markdown note and return
    [(section_title, line_text, [source_ids]), ...] for every bullet line.
    """
    results = []
    section = "(before first section)"
    for raw in note_text.splitlines():
        line = raw.strip()
        if line.startswith("###"):
            section = line.lstrip("#").strip()
            continue
        if not line.startswith("- "):
            continue
        body = line[2:].strip()
        tags = []
        match = TAG_PATTERN.search(body)
        if match:
            tags = [t.strip() for t in match.group(1).split(",") if t.strip()]
            body = TAG_PATTERN.sub("", body).strip()
        results.append((section, body, tags))
    return results


def collect_absent_source_ids(case):
    """
    Source ids whose data element is explicitly marked as absent in the input
    (available=false or documented=false).
    """
    absent = set()

    def walk(node):
        if isinstance(node, dict):
            sid = node.get("source_id")
            if isinstance(sid, str):
                if node.get("available") is False or node.get("documented") is False:
                    absent.add(sid)
            for value in node.values():
                walk(value)
        elif isinstance(node, list):
            for item in node:
                walk(item)

    walk(case)
    return absent


def strip_source_tags(note_text):
    """
    Remove evidence tags to produce the clean clinical version of the note.

    Both versions matter: the tagged version is the verification artefact
    (it is what makes traceability auditable), while the clean version is what
    would actually be filed in the record.
    """
    cleaned = []
    for line in note_text.splitlines():
        line = TAG_PATTERN.sub("", line)
        line = re.sub(r"\s+$", "", line)
        line = re.sub(r"^(\s*)-\s+-\s+", r"\1- ", line)  # tidy double bullets
        cleaned.append(line)
    return "\n".join(cleaned)


def _is_absence_section(section_title):
    """
    Sections whose purpose is to enumerate what is absent. A statement here is
    an absence statement by virtue of where it sits, even if the sentence
    itself contains no absence wording. Without this, prompt v1.3 (which
    correctly instructs the model to cite the absent element's source_id in
    the Missing Data list) causes every such line to be flagged.
    """
    return section_title.strip().lower().startswith("missing data")


def check_edited_note(note_text, case):
    """
    Re-validate a physician-edited note.

    Returns a dict of findings:
      unknown_tags        - cites a source_id that does not exist in the input
      absence_conflicts   - asserts content under a source marked absent
      cross_section       - same source cited as both present and absent
      untagged_additions  - bullet with no source tag at all
    """
    valid_ids = collect_source_ids(case) | {"NO_DATA"}
    absent_ids = collect_absent_source_ids(case)

    lines = parse_tagged_lines(note_text)

    unknown_tags, absence_conflicts, untagged = [], [], []
    by_tag = {}

    for section, body, tags in lines:
        if not body:
            continue
        if not tags:
            untagged.append((section, body))
            continue
        bad = [t for t in tags if t not in valid_ids]
        if bad:
            unknown_tags.append((section, body, bad))

        states_absence = _is_absence_section(section) or _has_absence_marker(body)

        for tag in tags:
            if tag == "NO_DATA":
                continue
            by_tag.setdefault(tag, []).append((section, body, states_absence))
            if tag in absent_ids and not states_absence:
                absence_conflicts.append((section, body, tag))

    cross_section = []
    for tag, entries in by_tag.items():
        if len(entries) < 2:
            continue
        absent_lines = [(s, b) for s, b, a in entries if a]
        present_lines = [(s, b) for s, b, a in entries if not a]
        if absent_lines and present_lines:
            cross_section.append((tag, present_lines, absent_lines))

    return {
        "unknown_tags": unknown_tags,
        "absence_conflicts": absence_conflicts,
        "cross_section": cross_section,
        "untagged_additions": untagged,
        "total_flags": (
            len(unknown_tags) + len(absence_conflicts)
            + len(cross_section) + len(untagged)
        ),
    }


def _write_row(path, row):
    exists = os.path.isfile(path)
    with open(path, "a", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=AUDIT_FIELDS)
        if not exists:
            writer.writeheader()
        writer.writerow({k: row.get(k, "") for k in AUDIT_FIELDS})


def append_audit(row, path=AUDIT_LOG):
    """
    Append one review event to the CSV audit trail.

    An audit trail must never silently lose an entry. If the primary file is
    locked (commonly because it is open in Excel on Windows), the entry is
    written to a timestamped fallback file instead of failing.

    Returns (path_written, note) so the UI can tell the reviewer what happened.
    """
    try:
        _write_row(path, row)
        return path, None
    except PermissionError:
        stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        base, ext = os.path.splitext(path)
        fallback = f"{base}_{stamp}{ext}"
        try:
            _write_row(fallback, row)
            return fallback, (
                f"'{path}' was locked (it is probably open in Excel). "
                f"The entry was saved to '{fallback}' instead — close Excel and "
                "merge the files, or keep them as separate session logs."
            )
        except Exception as exc:  # noqa: BLE001
            return None, f"Audit entry could NOT be saved: {exc}"
    except Exception as exc:  # noqa: BLE001
        return None, f"Audit entry could NOT be saved: {exc}"


def now_iso():
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")
